- name: Check elasticsearch process
  sudo_user: elasticsearch
  shell: ps -ef|grep -v grep | grep elasticsearch-5.6.3|wc -l
  register: result

- name: Start elasticsearch if not started already
  sudo_user: "elasticsearch"
 # shell: 'cd /opt/ems/els/elasticsearch-5.6.3/'
  script: els.sh
  #shell: bin/elasticsearch
  #args:
   # chdir: /opt/ems/els/elasticsearch-5.6.3/
  when: result.stdout == "0"


