- name: get the username running the deploy
  local_action: command whoami
  register: username_on_the_host

- debug: var=username_on_the_host

- name: Start elasticsearch if not started already
  sudo_user: elasticsearch
#  remote_user: elasticsearch
#  become: true
#  become_method: sudo
  script: els.sh
#  shell: ./elasticsearch
#  args:
#    chdir: /opt/ems/els/elasticsearch-5.6.3/bin
  #when: result.stdout == "0"
...

