



---
 - hosts: all
   tasks:
    - name: finding debug msg
    - debug:
      msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

    - name: finding host loopback
    - debug:
      msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
      when: ansible_default_ipv4.gateway is defined

    - name: finding uptime
    - shell: /usr/bin/uptime
      register: result
    - name: regostering a value
    - debug:
      var: result
      verbosity: 2

    - name: Display all variables/facts known for a host
      debug:
      var: hostvars[inventory_hostname]
      verbosity: 4

