

--
 - hosts: vm1 , localhost
   tasks:
   - name: just test file wether it is exist or not
     stat:
      path: /tmp/file.txt
     register: stat_result

   - name: Create the file, if it doesnt exist already
     file:
      path: /tmp/file.txt
      state: touch
     when: stat_result.stat.exists == False
...
     
