---
 - hosts: all
   tasks:
     - name: install apache using conditional statements
       yum: name=httpd  state=installed
       service: name=httpd state=started
       when: ansible_os_family == "Redhat" 

     - name: install apache for ubuntu
       apt: pkg=apache2 state=installed
       service: name=apache2 state=started
       when: ansible_os_family == "Ubuntu"


     - name: create directory for redhat family
       file: path=/tmp/ansi  state=directory
       owner: root
       group: root
       when: ansible_os_family == "Redhat"

     - name: create file for ubuntu family
       file: path=/mnt/test   state=touch
       owner: root
       group: root
       when: ansible_os_family == "Ubuntu"
 
