

---
 - hosts: devservers
   tasks:
    - name: install httpd
      yum: name=httpd state=installed

    - name: install php and libs
      yum: name={{ item }} state=absent
      with_items:
       - php-xml
       - php
       - php-zip
       - php-mbstring
       - php-mysqlnd
       - php-gd

